server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-server
  # rabbitmq 연동 (포트번호: 5672)
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id: bank-server
          uri: lb://BANK-SERVER
          predicates:
            - Path=/bank-server/**
        - id: news-server
          uri: lb://NEWS-SERVER
          predicates:
            - Path=/news-service/**
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges , busrefresh




